[package]

name = "open"
version = "1.0.0"
authors = ["Sebastian Thiel <byronimo@gmail.com>"]
license = "MIT"
repository = "https://github.com/Byron/open-rs"
keywords = ["open", "xdg-open", "start", "launch"]
documentation = "http://byron.github.io/open-rs"
